POST http://localhost:8000
Content-Type: application/json

{"position": "second_hand", "retry": 0, "hero_play": false, "crystal": 6, "round": 12,
"rivalHeroDetails": {
    "description": "# CFM_652: 23, GDB_320: 19",
    "cardId": "HERO_09", 
    "attack": 0, 
    "hp": 29,
    "entityId": "0",
    "isActive": true,
    "playedRound": -1,
    "card": {
        "isImmune": false
    }
},
"player_hand_cards": [
        {
            "cardId": "NX2_019", 
            "attack": 0, 
            "hp": 1, 
            "entityId": "1", 
            "isActive": true,
            "playedRound": -1,
            "card": {
                "isImmune": false, 
                "isActive": false
            }
        },
        {
            "cardId": "NX2_019", 
            "attack": 0, 
            "hp": 1, 
            "entityId": "2", 
            "isActive": true,
            "playedRound": -1,
            "card": {
                "isImmune": false, 
                "isActive": false
            }
        }
], 
"player_deck_cards": [], 
"played_actions": [], 
"rival_battle_cards": [
        {
            "description": "# CFM_652: 23, GDB_320: 19",
            "cardId": "GDB_320", 
            "attack": 4, 
            "hp": 5, 
            "entityId": "3", 
            "isActive": false,
            "playedRound": -1,
            "card": {
                "isLifesteal": false,
                "isImmune": false,
                "isTaunt": true
            }
        },
        {
            "cardId": "SW_444", 
            "attack": 1, 
            "hp": 5, 
            "entityId": "4", 
            "isActive": false,
            "playedRound": -1,
            "card": {
                "isImmune": false
            }
        },
        {
            "cardId": "SW_446", 
            "attack": 1, 
            "hp": 2, 
            "entityId": "5", 
            "isActive": false,
            "playedRound": -1,
            "card": {
                "isImmune": false
            }
        }
    ],
"companion_battle_cards": [
        {
            "cardId": "GVG_009",
            "attack": 3,
            "hp": 1,
            "entityId": "10",
            "isActive": false,
            "playedRound": -1,
            "description": "CFM_652: 28, GDB_320: 24",
            "card": {
                "isImmune": false
            }
        },
        {
            "cardId": "REV_290",
            "attack": 0, 
            "hp": 3, 
            "entityId": "6", 
            "isActive": true,
            "playedRound": -1,
            "card": {
                "isImmune": false
            }
        },
        {
            "cardId": "SW_446", 
            "attack": 1, 
            "hp": 2, 
            "entityId": "7", 
            "isActive": true,
            "playedRound": -1,
            "card": {
                "isImmune": false
            }
        },
        {
            "cardId": "SW_444", 
            "attack": 2, 
            "hp": 3, 
            "entityId": "8", 
            "isActive": true,
            "playedRound": -1,
            "card": {
                "isImmune": false
            }
        },
        {
            "cardId": "VAC_512", 
            "attack": 3, 
            "hp": 4, 
            "entityId": "9", 
            "isActive": true,
            "playedRound": -1,
            "card": {
                "isImmune": false
            }
        }
    ], 
"companion_died": [], 
"companion_burst_cards": [], 
"attack_rival_hero": 0, 
"attack_me_hero":0,
"meHeroDetails":     {
        "cardId": "GVG_009",
        "attack": 3,
        "hp": 1,
        "isActive": false,
        "playedRound": -1,
        "entityId": "11",
        "card": {
            "isImmune": false, 
            "isActive": false
        }
    },
"secret_size": 0
}