POST http://localhost:8000
Content-Type: application/json

{
    "position": "second_hand",
    "hero_play": false,
    "round": 4,
    "crystal": 4,
    "player_hand_cards": [
        {
            "cardId": "SW_444",
            "attack": 2,
            "hp": 3,
            "entityId": "33",
            "cost": 2,
            "playedRound": 4,
            "isActive": false,
            "card": {
                "cardType": "MINION",
                "cost": 2,
                "atc": 2,
                "health": 3,
                "armor": 0,
                "damage": 0,
                "isAdjacentBuff": false,
                "isPoisonous": false,
                "isDeathRattle": false,
                "creatorEntityId": "",
                "isTaunt": false,
                "isDivineShield": false,
                "isAura": false,
                "isStealth": false,
                "isFrozen": false,
                "isExhausted": false,
                "isWindFury": false,
                "isBattlecry": true,
                "isDiscover": false,
                "isCantBeTargetedBySpells": false,
                "isCantBeTargetedByHeroPowers": false,
                "isCantBeTargetedByOpponents": false,
                "isElusive": false,
                "isSpawnTimeCount": true,
                "isDormantAwakenConditionEnchant": false,
                "isImmune": false,
                "cardRace": "UNKNOWN",
                "isModular": true,
                "creator": "",
                "isPremium": false,
                "controller": "",
                "isTitan": false,
                "spellPower": 0,
                "isDormant": false,
                "isAttackableByRush": false,
                "isImmuneWhileAttacking": false,
                "isReborn": false,
                "isTriggerVisual": false,
                "isLifesteal": false,
                "isCoinCard": false,
                "isUntouchable": false,
                "isLocationActionCooldown": false,
                "isRush": false,
                "isCantAttack": false,
                "overload": 0,
                "numTurnsInPlay": 0,
                "numTurnsInHand": 8,
                "entityId": "33",
                "entityName": "暮光欺诈者"
            }
        },
        {
            "cardId": "NX2_019",
            "attack": 0,
            "hp": 0,
            "entityId": "24",
            "cost": 1,
            "playedRound": 4,
            "isActive": true,
            "card": {
                "cardType": "SPELL",
                "cost": 1,
                "atc": 0,
                "health": 0,
                "armor": 0,
                "damage": 0,
                "isAdjacentBuff": false,
                "isPoisonous": false,
                "isDeathRattle": false,
                "creatorEntityId": "",
                "isTaunt": false,
                "isDivineShield": false,
                "isAura": false,
                "isStealth": false,
                "isFrozen": false,
                "isExhausted": false,
                "isWindFury": false,
                "isBattlecry": false,
                "isDiscover": false,
                "isCantBeTargetedBySpells": false,
                "isCantBeTargetedByHeroPowers": false,
                "isCantBeTargetedByOpponents": false,
                "isElusive": false,
                "isSpawnTimeCount": true,
                "isDormantAwakenConditionEnchant": false,
                "isImmune": false,
                "cardRace": "UNKNOWN",
                "isModular": true,
                "creator": "",
                "isPremium": false,
                "controller": "",
                "isTitan": false,
                "spellPower": 0,
                "isDormant": false,
                "isAttackableByRush": false,
                "isImmuneWhileAttacking": false,
                "isReborn": false,
                "isTriggerVisual": false,
                "isLifesteal": false,
                "isCoinCard": false,
                "isUntouchable": false,
                "isLocationActionCooldown": false,
                "isRush": false,
                "isCantAttack": false,
                "overload": 0,
                "numTurnsInPlay": 0,
                "numTurnsInHand": 1,
                "entityId": "24",
                "entityName": "UNKNOWN ENTITY"
            }
        }
    ],
    "player_deck_cards": [],
    "played_actions": [
        [
            {
                "cardId": "CORE_WON_065",
                "attack": 1,
                "hp": 2,
                "entityId": "13",
                "cost": 1,
                "playedRound": -1,
                "isActive": false,
                "card": {
                    "cardType": "MINION",
                    "cost": 1,
                    "atc": 1,
                    "health": 2,
                    "armor": 0,
                    "damage": 0,
                    "isAdjacentBuff": false,
                    "isPoisonous": false,
                    "isDeathRattle": false,
                    "creatorEntityId": "",
                    "isTaunt": false,
                    "isDivineShield": false,
                    "isAura": false,
                    "isStealth": false,
                    "isFrozen": false,
                    "isExhausted": false,
                    "isWindFury": false,
                    "isBattlecry": false,
                    "isDiscover": false,
                    "isCantBeTargetedBySpells": false,
                    "isCantBeTargetedByHeroPowers": false,
                    "isCantBeTargetedByOpponents": false,
                    "isElusive": false,
                    "isSpawnTimeCount": true,
                    "isDormantAwakenConditionEnchant": false,
                    "isImmune": false,
                    "cardRace": "DRAGON",
                    "isModular": true,
                    "creator": "",
                    "isPremium": false,
                    "controller": "",
                    "isTitan": false,
                    "spellPower": 0,
                    "isDormant": false,
                    "isAttackableByRush": false,
                    "isImmuneWhileAttacking": false,
                    "isReborn": false,
                    "isTriggerVisual": true,
                    "isLifesteal": false,
                    "isCoinCard": false,
                    "isUntouchable": false,
                    "isLocationActionCooldown": false,
                    "isRush": false,
                    "isCantAttack": false,
                    "overload": 0,
                    "numTurnsInPlay": 6,
                    "numTurnsInHand": 2,
                    "entityId": "13",
                    "entityName": "随船外科医师"
                }
            }
        ],
        [
            {
                "cardId": "VAC_512",
                "attack": 2,
                "hp": 5,
                "entityId": "16",
                "cost": 1,
                "playedRound": -1,
                "isActive": false,
                "card": {
                    "cardType": "MINION",
                    "cost": 1,
                    "atc": 2,
                    "health": 5,
                    "armor": 0,
                    "damage": 0,
                    "isAdjacentBuff": false,
                    "isPoisonous": false,
                    "isDeathRattle": false,
                    "creatorEntityId": "",
                    "isTaunt": false,
                    "isDivineShield": false,
                    "isAura": false,
                    "isStealth": false,
                    "isFrozen": false,
                    "isExhausted": false,
                    "isWindFury": false,
                    "isBattlecry": false,
                    "isDiscover": false,
                    "isCantBeTargetedBySpells": false,
                    "isCantBeTargetedByHeroPowers": false,
                    "isCantBeTargetedByOpponents": false,
                    "isElusive": false,
                    "isSpawnTimeCount": true,
                    "isDormantAwakenConditionEnchant": false,
                    "isImmune": false,
                    "cardRace": "UNDEAD",
                    "isModular": true,
                    "creator": "",
                    "isPremium": false,
                    "controller": "",
                    "isTitan": false,
                    "spellPower": 0,
                    "isDormant": false,
                    "isAttackableByRush": false,
                    "isImmuneWhileAttacking": false,
                    "isReborn": false,
                    "isTriggerVisual": true,
                    "isLifesteal": false,
                    "isCoinCard": false,
                    "isUntouchable": false,
                    "isLocationActionCooldown": false,
                    "isRush": false,
                    "isCantAttack": false,
                    "overload": 0,
                    "numTurnsInPlay": 4,
                    "numTurnsInHand": 4,
                    "entityId": "16",
                    "entityName": "心灵按摩师"
                }
            },
            {
                "cardId": "DRG_056",
                "attack": 2,
                "hp": 3,
                "entityId": "15",
                "cost": 2,
                "playedRound": -1,
                "isActive": false,
                "card": {
                    "cardType": "MINION",
                    "cost": 2,
                    "atc": 2,
                    "health": 3,
                    "armor": 0,
                    "damage": 0,
                    "isAdjacentBuff": false,
                    "isPoisonous": false,
                    "isDeathRattle": false,
                    "creatorEntityId": "",
                    "isTaunt": false,
                    "isDivineShield": false,
                    "isAura": false,
                    "isStealth": false,
                    "isFrozen": false,
                    "isExhausted": false,
                    "isWindFury": false,
                    "isBattlecry": false,
                    "isDiscover": false,
                    "isCantBeTargetedBySpells": false,
                    "isCantBeTargetedByHeroPowers": false,
                    "isCantBeTargetedByOpponents": false,
                    "isElusive": false,
                    "isSpawnTimeCount": true,
                    "isDormantAwakenConditionEnchant": false,
                    "isImmune": false,
                    "cardRace": "PIRATE",
                    "isModular": true,
                    "creator": "",
                    "isPremium": false,
                    "controller": "",
                    "isTitan": false,
                    "spellPower": 0,
                    "isDormant": false,
                    "isAttackableByRush": false,
                    "isImmuneWhileAttacking": false,
                    "isReborn": false,
                    "isTriggerVisual": false,
                    "isLifesteal": false,
                    "isCoinCard": false,
                    "isUntouchable": false,
                    "isLocationActionCooldown": false,
                    "isRush": false,
                    "isCantAttack": false,
                    "overload": 0,
                    "numTurnsInPlay": 4,
                    "numTurnsInHand": 1,
                    "entityId": "15",
                    "entityName": "空降歹徒"
                }
            },
            {
                "cardId": "WON_062",
                "attack": 3,
                "hp": 2,
                "entityId": "7",
                "cost": 1,
                "playedRound": -1,
                "isActive": false,
                "card": {
                    "cardType": "MINION",
                    "cost": 1,
                    "atc": 3,
                    "health": 2,
                    "armor": 0,
                    "damage": 0,
                    "isAdjacentBuff": false,
                    "isPoisonous": false,
                    "isDeathRattle": false,
                    "creatorEntityId": "",
                    "isTaunt": false,
                    "isDivineShield": false,
                    "isAura": false,
                    "isStealth": false,
                    "isFrozen": false,
                    "isExhausted": false,
                    "isWindFury": false,
                    "isBattlecry": true,
                    "isDiscover": false,
                    "isCantBeTargetedBySpells": false,
                    "isCantBeTargetedByHeroPowers": false,
                    "isCantBeTargetedByOpponents": false,
                    "isElusive": false,
                    "isSpawnTimeCount": true,
                    "isDormantAwakenConditionEnchant": false,
                    "isImmune": false,
                    "cardRace": "UNKNOWN",
                    "isModular": true,
                    "creator": "",
                    "isPremium": false,
                    "controller": "",
                    "isTitan": false,
                    "spellPower": 0,
                    "isDormant": false,
                    "isAttackableByRush": false,
                    "isImmuneWhileAttacking": false,
                    "isReborn": false,
                    "isTriggerVisual": false,
                    "isLifesteal": false,
                    "isCoinCard": false,
                    "isUntouchable": false,
                    "isLocationActionCooldown": false,
                    "isRush": false,
                    "isCantAttack": false,
                    "overload": 0,
                    "numTurnsInPlay": 4,
                    "numTurnsInHand": 3,
                    "entityId": "7",
                    "entityName": "暗影投弹手"
                }
            }
        ],
        [
            {
                "cardId": "GAME_005",
                "attack": 0,
                "hp": 0,
                "entityId": "81",
                "cost": 0,
                "playedRound": -1,
                "isActive": false,
                "card": {
                    "cardType": "SPELL",
                    "cost": 0,
                    "atc": 0,
                    "health": 0,
                    "armor": 0,
                    "damage": 0,
                    "isAdjacentBuff": false,
                    "isPoisonous": false,
                    "isDeathRattle": false,
                    "creatorEntityId": "",
                    "isTaunt": false,
                    "isDivineShield": false,
                    "isAura": false,
                    "isStealth": false,
                    "isFrozen": false,
                    "isExhausted": false,
                    "isWindFury": false,
                    "isBattlecry": false,
                    "isDiscover": false,
                    "isCantBeTargetedBySpells": false,
                    "isCantBeTargetedByHeroPowers": false,
                    "isCantBeTargetedByOpponents": false,
                    "isElusive": false,
                    "isSpawnTimeCount": true,
                    "isDormantAwakenConditionEnchant": false,
                    "isImmune": false,
                    "cardRace": "UNKNOWN",
                    "isModular": true,
                    "creator": "1",
                    "isPremium": false,
                    "controller": "",
                    "isTitan": false,
                    "spellPower": 0,
                    "isDormant": false,
                    "isAttackableByRush": false,
                    "isImmuneWhileAttacking": false,
                    "isReborn": false,
                    "isTriggerVisual": false,
                    "isLifesteal": false,
                    "isCoinCard": true,
                    "isUntouchable": false,
                    "isLocationActionCooldown": false,
                    "isRush": false,
                    "isCantAttack": false,
                    "overload": 0,
                    "numTurnsInPlay": 0,
                    "numTurnsInHand": 6,
                    "entityId": "81",
                    "entityName": "幸运币"
                }
            },
            {
                "cardId": "CORE_WON_065",
                "attack": 1,
                "hp": 3,
                "entityId": "17",
                "cost": 1,
                "playedRound": -1,
                "isActive": false,
                "card": {
                    "cardType": "MINION",
                    "cost": 1,
                    "atc": 1,
                    "health": 3,
                    "armor": 0,
                    "damage": 0,
                    "isAdjacentBuff": false,
                    "isPoisonous": false,
                    "isDeathRattle": false,
                    "creatorEntityId": "",
                    "isTaunt": false,
                    "isDivineShield": false,
                    "isAura": false,
                    "isStealth": false,
                    "isFrozen": false,
                    "isExhausted": false,
                    "isWindFury": false,
                    "isBattlecry": false,
                    "isDiscover": false,
                    "isCantBeTargetedBySpells": false,
                    "isCantBeTargetedByHeroPowers": false,
                    "isCantBeTargetedByOpponents": false,
                    "isElusive": false,
                    "isSpawnTimeCount": true,
                    "isDormantAwakenConditionEnchant": false,
                    "isImmune": false,
                    "cardRace": "DRAGON",
                    "isModular": true,
                    "creator": "",
                    "isPremium": false,
                    "controller": "",
                    "isTitan": false,
                    "spellPower": 0,
                    "isDormant": false,
                    "isAttackableByRush": false,
                    "isImmuneWhileAttacking": false,
                    "isReborn": false,
                    "isTriggerVisual": true,
                    "isLifesteal": false,
                    "isCoinCard": false,
                    "isUntouchable": false,
                    "isLocationActionCooldown": false,
                    "isRush": false,
                    "isCantAttack": false,
                    "overload": 0,
                    "numTurnsInPlay": 2,
                    "numTurnsInHand": 6,
                    "entityId": "17",
                    "entityName": "随船外科医师"
                }
            },
            {
                "cardId": "EX1_625t",
                "attack": 0,
                "hp": 0,
                "entityId": "83",
                "cost": 2,
                "playedRound": -1,
                "isActive": false,
                "card": {
                    "cardType": "HERO_POWER",
                    "cost": 2,
                    "atc": 0,
                    "health": 0,
                    "armor": 0,
                    "damage": 0,
                    "isAdjacentBuff": false,
                    "isPoisonous": false,
                    "isDeathRattle": false,
                    "creatorEntityId": "",
                    "isTaunt": false,
                    "isDivineShield": false,
                    "isAura": false,
                    "isStealth": false,
                    "isFrozen": false,
                    "isExhausted": false,
                    "isWindFury": false,
                    "isBattlecry": false,
                    "isDiscover": false,
                    "isCantBeTargetedBySpells": false,
                    "isCantBeTargetedByHeroPowers": false,
                    "isCantBeTargetedByOpponents": false,
                    "isElusive": false,
                    "isSpawnTimeCount": true,
                    "isDormantAwakenConditionEnchant": false,
                    "isImmune": false,
                    "cardRace": "UNKNOWN",
                    "isModular": true,
                    "creator": "12",
                    "isPremium": false,
                    "controller": "",
                    "isTitan": false,
                    "spellPower": 0,
                    "isDormant": false,
                    "isAttackableByRush": false,
                    "isImmuneWhileAttacking": false,
                    "isReborn": false,
                    "isTriggerVisual": false,
                    "isLifesteal": false,
                    "isCoinCard": false,
                    "isUntouchable": false,
                    "isLocationActionCooldown": false,
                    "isRush": false,
                    "isCantAttack": false,
                    "overload": 0,
                    "numTurnsInPlay": 8,
                    "numTurnsInHand": 0,
                    "entityId": "83",
                    "entityName": "心灵尖刺"
                }
            },
            {
                "cardId": "WON_062",
                "attack": 3,
                "hp": 3,
                "entityId": "26",
                "cost": 1,
                "playedRound": -1,
                "isActive": false,
                "card": {
                    "cardType": "MINION",
                    "cost": 1,
                    "atc": 3,
                    "health": 3,
                    "armor": 0,
                    "damage": 0,
                    "isAdjacentBuff": false,
                    "isPoisonous": false,
                    "isDeathRattle": false,
                    "creatorEntityId": "",
                    "isTaunt": false,
                    "isDivineShield": false,
                    "isAura": false,
                    "isStealth": false,
                    "isFrozen": false,
                    "isExhausted": false,
                    "isWindFury": false,
                    "isBattlecry": true,
                    "isDiscover": false,
                    "isCantBeTargetedBySpells": false,
                    "isCantBeTargetedByHeroPowers": false,
                    "isCantBeTargetedByOpponents": false,
                    "isElusive": false,
                    "isSpawnTimeCount": true,
                    "isDormantAwakenConditionEnchant": false,
                    "isImmune": false,
                    "cardRace": "UNKNOWN",
                    "isModular": true,
                    "creator": "",
                    "isPremium": false,
                    "controller": "",
                    "isTitan": false,
                    "spellPower": 0,
                    "isDormant": false,
                    "isAttackableByRush": false,
                    "isImmuneWhileAttacking": false,
                    "isReborn": false,
                    "isTriggerVisual": false,
                    "isLifesteal": false,
                    "isCoinCard": false,
                    "isUntouchable": false,
                    "isLocationActionCooldown": false,
                    "isRush": false,
                    "isCantAttack": false,
                    "overload": 0,
                    "numTurnsInPlay": 2,
                    "numTurnsInHand": 1,
                    "entityId": "26",
                    "entityName": "暗影投弹手"
                }
            }
        ]
    ],
    "rival_battle_cards": [
        {
            "cardId": "GDB_100",
            "attack": 3,
            "hp": 4,
            "entityId": "40",
            "cost": 4,
            "playedRound": 4,
            "isActive": true,
            "card": {
                "cardType": "MINION",
                "cost": 4,
                "atc": 3,
                "health": 4,
                "armor": 0,
                "damage": 0,
                "isAdjacentBuff": false,
                "isPoisonous": false,
                "isDeathRattle": true,
                "creatorEntityId": "",
                "isTaunt": true,
                "isDivineShield": false,
                "isAura": false,
                "isStealth": false,
                "isFrozen": false,
                "isExhausted": true,
                "isWindFury": false,
                "isBattlecry": false,
                "isDiscover": false,
                "isCantBeTargetedBySpells": false,
                "isCantBeTargetedByHeroPowers": false,
                "isCantBeTargetedByOpponents": false,
                "isElusive": false,
                "isSpawnTimeCount": true,
                "isDormantAwakenConditionEnchant": false,
                "isImmune": false,
                "cardRace": "UNKNOWN",
                "isModular": false,
                "creator": "",
                "isPremium": true,
                "controller": "",
                "isTitan": false,
                "spellPower": 0,
                "isDormant": false,
                "isAttackableByRush": false,
                "isImmuneWhileAttacking": false,
                "isReborn": false,
                "isTriggerVisual": false,
                "isLifesteal": false,
                "isCoinCard": false,
                "isUntouchable": false,
                "isLocationActionCooldown": false,
                "isRush": false,
                "isCantAttack": false,
                "overload": 0,
                "numTurnsInPlay": 1,
                "numTurnsInHand": 7,
                "entityId": "40",
                "entityName": "阿肯尼特防护水晶"
            }
        }
    ],
    "companion_battle_cards": [
        {
            "cardId": "CORE_WON_065",
            "attack": 1,
            "hp": 2,
            "entityId": "13",
            "cost": 1,
            "playedRound": 3,
            "isActive": true,
            "card": {
                "cardType": "MINION",
                "cost": 1,
                "atc": 1,
                "health": 2,
                "armor": 0,
                "damage": 0,
                "isAdjacentBuff": false,
                "isPoisonous": false,
                "isDeathRattle": false,
                "creatorEntityId": "",
                "isTaunt": false,
                "isDivineShield": false,
                "isAura": false,
                "isStealth": false,
                "isFrozen": false,
                "isExhausted": false,
                "isWindFury": false,
                "isBattlecry": false,
                "isDiscover": false,
                "isCantBeTargetedBySpells": false,
                "isCantBeTargetedByHeroPowers": false,
                "isCantBeTargetedByOpponents": false,
                "isElusive": false,
                "isSpawnTimeCount": true,
                "isDormantAwakenConditionEnchant": false,
                "isImmune": false,
                "cardRace": "DRAGON",
                "isModular": true,
                "creator": "",
                "isPremium": false,
                "controller": "",
                "isTitan": false,
                "spellPower": 0,
                "isDormant": false,
                "isAttackableByRush": false,
                "isImmuneWhileAttacking": false,
                "isReborn": false,
                "isTriggerVisual": true,
                "isLifesteal": false,
                "isCoinCard": false,
                "isUntouchable": false,
                "isLocationActionCooldown": false,
                "isRush": false,
                "isCantAttack": false,
                "overload": 0,
                "numTurnsInPlay": 6,
                "numTurnsInHand": 2,
                "entityId": "13",
                "entityName": "随船外科医师"
            }
        },
        {
            "cardId": "CFM_637",
            "attack": 1,
            "hp": 2,
            "entityId": "11",
            "cost": 1,
            "playedRound": 3,
            "isActive": true,
            "card": {
                "cardType": "MINION",
                "cost": 1,
                "atc": 1,
                "health": 2,
                "armor": 0,
                "damage": 0,
                "isAdjacentBuff": false,
                "isPoisonous": false,
                "isDeathRattle": false,
                "creatorEntityId": "",
                "isTaunt": false,
                "isDivineShield": false,
                "isAura": false,
                "isStealth": false,
                "isFrozen": false,
                "isExhausted": false,
                "isWindFury": false,
                "isBattlecry": false,
                "isDiscover": false,
                "isCantBeTargetedBySpells": false,
                "isCantBeTargetedByHeroPowers": false,
                "isCantBeTargetedByOpponents": false,
                "isElusive": false,
                "isSpawnTimeCount": true,
                "isDormantAwakenConditionEnchant": false,
                "isImmune": false,
                "cardRace": "PIRATE",
                "isModular": true,
                "creator": "",
                "isPremium": false,
                "controller": "",
                "isTitan": false,
                "spellPower": 0,
                "isDormant": false,
                "isAttackableByRush": false,
                "isImmuneWhileAttacking": false,
                "isReborn": false,
                "isTriggerVisual": false,
                "isLifesteal": false,
                "isCoinCard": false,
                "isUntouchable": false,
                "isLocationActionCooldown": false,
                "isRush": false,
                "isCantAttack": false,
                "overload": 0,
                "numTurnsInPlay": 6,
                "numTurnsInHand": 0,
                "entityId": "11",
                "entityName": "海盗帕奇斯"
            }
        },
        {
            "cardId": "VAC_512",
            "attack": 2,
            "hp": 5,
            "entityId": "16",
            "cost": 1,
            "playedRound": 3,
            "isActive": true,
            "card": {
                "cardType": "MINION",
                "cost": 1,
                "atc": 2,
                "health": 5,
                "armor": 0,
                "damage": 0,
                "isAdjacentBuff": false,
                "isPoisonous": false,
                "isDeathRattle": false,
                "creatorEntityId": "",
                "isTaunt": false,
                "isDivineShield": false,
                "isAura": false,
                "isStealth": false,
                "isFrozen": false,
                "isExhausted": false,
                "isWindFury": false,
                "isBattlecry": false,
                "isDiscover": false,
                "isCantBeTargetedBySpells": false,
                "isCantBeTargetedByHeroPowers": false,
                "isCantBeTargetedByOpponents": false,
                "isElusive": false,
                "isSpawnTimeCount": true,
                "isDormantAwakenConditionEnchant": false,
                "isImmune": false,
                "cardRace": "UNDEAD",
                "isModular": true,
                "creator": "",
                "isPremium": false,
                "controller": "",
                "isTitan": false,
                "spellPower": 0,
                "isDormant": false,
                "isAttackableByRush": false,
                "isImmuneWhileAttacking": false,
                "isReborn": false,
                "isTriggerVisual": true,
                "isLifesteal": false,
                "isCoinCard": false,
                "isUntouchable": false,
                "isLocationActionCooldown": false,
                "isRush": false,
                "isCantAttack": false,
                "overload": 0,
                "numTurnsInPlay": 4,
                "numTurnsInHand": 4,
                "entityId": "16",
                "entityName": "心灵按摩师"
            }
        },
        {
            "cardId": "DRG_056",
            "attack": 2,
            "hp": 3,
            "entityId": "15",
            "cost": 2,
            "playedRound": 3,
            "isActive": true,
            "card": {
                "cardType": "MINION",
                "cost": 2,
                "atc": 2,
                "health": 3,
                "armor": 0,
                "damage": 0,
                "isAdjacentBuff": false,
                "isPoisonous": false,
                "isDeathRattle": false,
                "creatorEntityId": "",
                "isTaunt": false,
                "isDivineShield": false,
                "isAura": false,
                "isStealth": false,
                "isFrozen": false,
                "isExhausted": false,
                "isWindFury": false,
                "isBattlecry": false,
                "isDiscover": false,
                "isCantBeTargetedBySpells": false,
                "isCantBeTargetedByHeroPowers": false,
                "isCantBeTargetedByOpponents": false,
                "isElusive": false,
                "isSpawnTimeCount": true,
                "isDormantAwakenConditionEnchant": false,
                "isImmune": false,
                "cardRace": "PIRATE",
                "isModular": true,
                "creator": "",
                "isPremium": false,
                "controller": "",
                "isTitan": false,
                "spellPower": 0,
                "isDormant": false,
                "isAttackableByRush": false,
                "isImmuneWhileAttacking": false,
                "isReborn": false,
                "isTriggerVisual": false,
                "isLifesteal": false,
                "isCoinCard": false,
                "isUntouchable": false,
                "isLocationActionCooldown": false,
                "isRush": false,
                "isCantAttack": false,
                "overload": 0,
                "numTurnsInPlay": 4,
                "numTurnsInHand": 1,
                "entityId": "15",
                "entityName": "空降歹徒"
            }
        },
        {
            "cardId": "WON_062",
            "attack": 3,
            "hp": 2,
            "entityId": "7",
            "cost": 1,
            "playedRound": 3,
            "isActive": true,
            "card": {
                "cardType": "MINION",
                "cost": 1,
                "atc": 3,
                "health": 2,
                "armor": 0,
                "damage": 0,
                "isAdjacentBuff": false,
                "isPoisonous": false,
                "isDeathRattle": false,
                "creatorEntityId": "",
                "isTaunt": false,
                "isDivineShield": false,
                "isAura": false,
                "isStealth": false,
                "isFrozen": false,
                "isExhausted": false,
                "isWindFury": false,
                "isBattlecry": true,
                "isDiscover": false,
                "isCantBeTargetedBySpells": false,
                "isCantBeTargetedByHeroPowers": false,
                "isCantBeTargetedByOpponents": false,
                "isElusive": false,
                "isSpawnTimeCount": true,
                "isDormantAwakenConditionEnchant": false,
                "isImmune": false,
                "cardRace": "UNKNOWN",
                "isModular": true,
                "creator": "",
                "isPremium": false,
                "controller": "",
                "isTitan": false,
                "spellPower": 0,
                "isDormant": false,
                "isAttackableByRush": false,
                "isImmuneWhileAttacking": false,
                "isReborn": false,
                "isTriggerVisual": false,
                "isLifesteal": false,
                "isCoinCard": false,
                "isUntouchable": false,
                "isLocationActionCooldown": false,
                "isRush": false,
                "isCantAttack": false,
                "overload": 0,
                "numTurnsInPlay": 4,
                "numTurnsInHand": 3,
                "entityId": "7",
                "entityName": "暗影投弹手"
            }
        },
        {
            "cardId": "WON_062",
            "attack": 3,
            "hp": 3,
            "entityId": "26",
            "cost": 1,
            "playedRound": 3,
            "isActive": true,
            "card": {
                "cardType": "MINION",
                "cost": 1,
                "atc": 3,
                "health": 3,
                "armor": 0,
                "damage": 0,
                "isAdjacentBuff": false,
                "isPoisonous": false,
                "isDeathRattle": false,
                "creatorEntityId": "",
                "isTaunt": false,
                "isDivineShield": false,
                "isAura": false,
                "isStealth": false,
                "isFrozen": false,
                "isExhausted": false,
                "isWindFury": false,
                "isBattlecry": true,
                "isDiscover": false,
                "isCantBeTargetedBySpells": false,
                "isCantBeTargetedByHeroPowers": false,
                "isCantBeTargetedByOpponents": false,
                "isElusive": false,
                "isSpawnTimeCount": true,
                "isDormantAwakenConditionEnchant": false,
                "isImmune": false,
                "cardRace": "UNKNOWN",
                "isModular": true,
                "creator": "",
                "isPremium": false,
                "controller": "",
                "isTitan": false,
                "spellPower": 0,
                "isDormant": false,
                "isAttackableByRush": false,
                "isImmuneWhileAttacking": false,
                "isReborn": false,
                "isTriggerVisual": false,
                "isLifesteal": false,
                "isCoinCard": false,
                "isUntouchable": false,
                "isLocationActionCooldown": false,
                "isRush": false,
                "isCantAttack": false,
                "overload": 0,
                "numTurnsInPlay": 2,
                "numTurnsInHand": 1,
                "entityId": "26",
                "entityName": "暗影投弹手"
            }
        },
        {
            "cardId": "CORE_WON_065",
            "attack": 1,
            "hp": 3,
            "entityId": "17",
            "cost": 1,
            "playedRound": 3,
            "isActive": true,
            "card": {
                "cardType": "MINION",
                "cost": 1,
                "atc": 1,
                "health": 3,
                "armor": 0,
                "damage": 0,
                "isAdjacentBuff": false,
                "isPoisonous": false,
                "isDeathRattle": false,
                "creatorEntityId": "",
                "isTaunt": false,
                "isDivineShield": false,
                "isAura": false,
                "isStealth": false,
                "isFrozen": false,
                "isExhausted": false,
                "isWindFury": false,
                "isBattlecry": false,
                "isDiscover": false,
                "isCantBeTargetedBySpells": false,
                "isCantBeTargetedByHeroPowers": false,
                "isCantBeTargetedByOpponents": false,
                "isElusive": false,
                "isSpawnTimeCount": true,
                "isDormantAwakenConditionEnchant": false,
                "isImmune": false,
                "cardRace": "DRAGON",
                "isModular": true,
                "creator": "",
                "isPremium": false,
                "controller": "",
                "isTitan": false,
                "spellPower": 0,
                "isDormant": false,
                "isAttackableByRush": false,
                "isImmuneWhileAttacking": false,
                "isReborn": false,
                "isTriggerVisual": true,
                "isLifesteal": false,
                "isCoinCard": false,
                "isUntouchable": false,
                "isLocationActionCooldown": false,
                "isRush": false,
                "isCantAttack": false,
                "overload": 0,
                "numTurnsInPlay": 2,
                "numTurnsInHand": 6,
                "entityId": "17",
                "entityName": "随船外科医师"
            }
        }
    ],
    "companion_died": [],
    "companion_burst_cards": [],
    "rivalHeroDetails": {
        "cardId": "HERO_09j",
        "attack": 0,
        "hp": 21,
        "entityId": "79",
        "cost": 0,
        "playedRound": -1,
        "isActive": true,
        "card": {
            "cardType": "HERO",
            "cost": 0,
            "atc": 0,
            "health": 40,
            "armor": 0,
            "damage": 19,
            "isAdjacentBuff": false,
            "isPoisonous": false,
            "isDeathRattle": false,
            "creatorEntityId": "",
            "isTaunt": false,
            "isDivineShield": false,
            "isAura": false,
            "isStealth": false,
            "isFrozen": false,
            "isExhausted": false,
            "isWindFury": false,
            "isBattlecry": false,
            "isDiscover": false,
            "isCantBeTargetedBySpells": false,
            "isCantBeTargetedByHeroPowers": false,
            "isCantBeTargetedByOpponents": false,
            "isElusive": false,
            "isSpawnTimeCount": true,
            "isDormantAwakenConditionEnchant": false,
            "isImmune": false,
            "cardRace": "UNKNOWN",
            "isModular": false,
            "creator": "",
            "isPremium": true,
            "controller": "",
            "isTitan": false,
            "spellPower": 0,
            "isDormant": false,
            "isAttackableByRush": false,
            "isImmuneWhileAttacking": false,
            "isReborn": false,
            "isTriggerVisual": false,
            "isLifesteal": false,
            "isCoinCard": false,
            "isUntouchable": false,
            "isLocationActionCooldown": false,
            "isRush": false,
            "isCantAttack": false,
            "overload": 0,
            "numTurnsInPlay": 8,
            "numTurnsInHand": 0,
            "entityId": "79",
            "entityName": "织光者泽瑞拉"
        }
    },
    "meHeroDetails": {
        "cardId": "HERO_09",
        "attack": 0,
        "hp": 24,
        "entityId": "77",
        "cost": 0,
        "playedRound": -1,
        "isActive": false,
        "card": {
            "cardType": "HERO",
            "cost": 0,
            "atc": 0,
            "health": 30,
            "armor": 0,
            "damage": 6,
            "isAdjacentBuff": false,
            "isPoisonous": false,
            "isDeathRattle": false,
            "creatorEntityId": "",
            "isTaunt": false,
            "isDivineShield": false,
            "isAura": false,
            "isStealth": false,
            "isFrozen": false,
            "isExhausted": false,
            "isWindFury": false,
            "isBattlecry": false,
            "isDiscover": false,
            "isCantBeTargetedBySpells": false,
            "isCantBeTargetedByHeroPowers": false,
            "isCantBeTargetedByOpponents": false,
            "isElusive": false,
            "isSpawnTimeCount": true,
            "isDormantAwakenConditionEnchant": false,
            "isImmune": false,
            "cardRace": "UNKNOWN",
            "isModular": true,
            "creator": "",
            "isPremium": false,
            "controller": "",
            "isTitan": false,
            "spellPower": 0,
            "isDormant": false,
            "isAttackableByRush": false,
            "isImmuneWhileAttacking": false,
            "isReborn": false,
            "isTriggerVisual": false,
            "isLifesteal": false,
            "isCoinCard": false,
            "isUntouchable": false,
            "isLocationActionCooldown": false,
            "isRush": false,
            "isCantAttack": false,
            "overload": 0,
            "numTurnsInPlay": 8,
            "numTurnsInHand": 0,
            "entityId": "77",
            "entityName": "安度因·乌瑞恩"
        }
    },
    "attack_rival_hero": 0,
    "attack_me_hero": 0,
    "secret_size": 1,
    "meHeroPowerDetails": {
        "cardId": "EX1_625t",
        "attack": 0,
        "hp": 0,
        "entityId": "83",
        "cost": 2,
        "playedRound": -1,
        "isActive": false,
        "card": {
            "cardType": "HERO_POWER",
            "cost": 2,
            "atc": 0,
            "health": 0,
            "armor": 0,
            "damage": 0,
            "isAdjacentBuff": false,
            "isPoisonous": false,
            "isDeathRattle": false,
            "creatorEntityId": "",
            "isTaunt": false,
            "isDivineShield": false,
            "isAura": false,
            "isStealth": false,
            "isFrozen": false,
            "isExhausted": false,
            "isWindFury": false,
            "isBattlecry": false,
            "isDiscover": false,
            "isCantBeTargetedBySpells": false,
            "isCantBeTargetedByHeroPowers": false,
            "isCantBeTargetedByOpponents": false,
            "isElusive": false,
            "isSpawnTimeCount": true,
            "isDormantAwakenConditionEnchant": false,
            "isImmune": false,
            "cardRace": "UNKNOWN",
            "isModular": true,
            "creator": "12",
            "isPremium": false,
            "controller": "",
            "isTitan": false,
            "spellPower": 0,
            "isDormant": false,
            "isAttackableByRush": false,
            "isImmuneWhileAttacking": false,
            "isReborn": false,
            "isTriggerVisual": false,
            "isLifesteal": false,
            "isCoinCard": false,
            "isUntouchable": false,
            "isLocationActionCooldown": false,
            "isRush": false,
            "isCantAttack": false,
            "overload": 0,
            "numTurnsInPlay": 8,
            "numTurnsInHand": 0,
            "entityId": "83",
            "entityName": "心灵尖刺"
        }
    }
}